// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Database.ClassLibrary.DataAccess;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Database.ClassLibrary.DatabaseFirst
{
    public partial class CartToCart:IEntity
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdCartToCart { get; set; }
        public decimal Amount { get; set; }
        public int SenderUserIdForCartToCart { get; set; }
        public int ReceiverUserIdForCartToCart { get; set; }

        public virtual User ReceiverUserIdForCartToCartNavigation { get; set; }
        public virtual User SenderUserIdForCartToCartNavigation { get; set; }
    }
}