// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Database.ClassLibrary.DataAccess;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Database.ClassLibrary.DatabaseFirst
{
    public partial class User : IEntity
    {
        public User()
        {
            CartToCartReceiverUserIdForCartToCartNavigation = new HashSet<CartToCart>();
            CartToCartSenderUserIdForCartToCartNavigation = new HashSet<CartToCart>();
            Wallet = new HashSet<Wallet>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdUser { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string City { get; set; }
        public DateTime? When { get; set; }
        public string PhoneNumber { get; set; }

        public virtual ICollection<CartToCart> CartToCartReceiverUserIdForCartToCartNavigation { get; set; }
        public virtual ICollection<CartToCart> CartToCartSenderUserIdForCartToCartNavigation { get; set; }
        public virtual ICollection<Wallet> Wallet { get; set; }
    }
}