// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Database.ClassLibrary.DataAccess;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Database.ClassLibrary.DatabaseFirst
{
    public partial class Wallet : IEntity
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdWallet { get; set; }
        public string Currency { get; set; }
        public decimal Balance { get; set; }
        public int UserIdForWallet { get; set; }

        public virtual User UserIdForWalletNavigation { get; set; }
    }
}